version: '3.7'

services:
  shuffle:
    image: 'sema/shuffle:latest'
    container_name: 'aces-high'
    environment:
      - 'SPRING_PROFILES_ACTIVE=interleave-shuffle'
    ports:
      - '127.0.0.1:8081:8080'
