/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.sema.shuffle;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication
@EnableJpaRepositories(basePackages = "io.sema.shuffle")
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
